name: Pipeline do Netlify

on:
  workflow_dispatch:  
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy do Site no Netlify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        
      - name: Setup do Node.js para Netlify CLI
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instala o Netlify CLI
        run: npm install -g netlify-cli

      - name: Atualiza site na Netlify
        env:
          ENV_NETLIFY_AUTH_TOKEN: $｛｛ secrets.NETLIFY_AUTH_TOKEN ｝｝
          ENV_NETLIFY_SITE_ID: $｛｛ secrets.NETLIFY_SITE_ID ｝｝     
        run: netlify deploy --site=$ENV_NETLIFY_SITE_ID --auth=$ENV_NETLIFY_AUTH_TOKEN --dir="." --prod